purchase_type: on_demand
subnet_id: subnet-34ea6950
num_instances: 1
key_name: qingpeng-zhang
security_group_ids: sg-acb670ca
instance_type: m4.xlarge
tag_name: es-qingpeng
vol_size: 200
role: master
use_eips: true
