purchase_type: spot
subnet_id: subnet-34ea6950
price: 0.13
num_instances: 3
key_name: qingpeng-zhang
security_group_ids: sg-acb670ca
instance_type: m4.large
tag_name: spark-cluster-qingpeng
vol_size: 100
role: worker
use_eips: true
